project_id = "rmwzpnlssmsvtmuuberl"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.generate-summary]
verify_jwt = false